import Head from 'next/head'
import Features from '../features_section/features'
import Navbar from '../header/navbar'
import Hero from '../hero_section/hero'


export default function Layout({ children }) {

  return (
    <>
    <div className="bg-white">
       <Navbar/>
       <Head>
        <title>Arthaich</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/mark.svg" />
      </Head>
     
      <main>{children}</main>
      </div>
    </>
  )
}