import Head from 'next/head';
import Script from 'next/script';
import Footer from '../footer/footer';
import Navbar from '../header/navbar';


export default function Layout({ children, router }) {


  return (
    <>
      <div className="bg-white">
        <Navbar router={router} user={children.props.user}/>
        <Head>
          <title>Mattech</title>
          <meta name="description" content="Generated by ECO² Colombia" />
          <Script
            type="text/javascript"
            src="http://localhost:1337/plugins/strapi-stripe/static/stripe.js"
          />
          <link rel="icon" href="/Mlogo.ico" />
        </Head>

        {children}

        <Footer />
      </div>
    </>
  );
}
