import Head from "next/head";
import Script from "next/script";
import Footer from "../footer/footer";
// import Navbar from '../header/navbar';
import { Header } from "../shared/Header";

export default function Layout({ children, router }) {
  return (
    <>
      <div className="dark:bg-darkColor bg-zinc-300">
        <Header router={router} user={children.props.user} />
        <Head>
          <title>ECO²</title>
          <meta name="description" content="Generated by ECO² Colombia" />
          <Script
            type="text/javascript"
            src="http://localhost:1337/plugins/strapi-stripe/static/stripe.js"
          />
          <link rel="icon" href="/eco2it_logo.jpeg" />
        </Head>

        {children}

        <Footer />
      </div>
    </>
  );
}
