import Head from 'next/head';
import Footer from '../footer/footer';
import { Header } from '../shared/Header/Header';

export default function Layout({ children, router }) {
  return (
    <>
      <div className="bg-no-repeat aspect-video w-full bg-cover bg-center bg-[url('/bgLight.svg')] dark:bg-[url('/bgDark.svg')]  overflow-y-scroll h-screen">
        <Header router={router} user={children.props.user} />
        <Head>
          <title>ECO²</title>
          <meta name="description" content="Generated by ECO² Colombia" />
          <link rel="icon" href="/eco2it_logo.jpeg" />
        </Head>
        {children}
        <Footer />
      </div>
    </>
  );
}
