const domain = [
  'Ciencias de la salud',
  'Ciencias humanas y sociales',
  'Ciencias, tecnología, ingeniería y matemáticas (STEM)',
  'Ciencias naturales',
  'Derecho',
  'Negocios y comercio',
  'Artes y diseño',
  'Educación',
  'Agricultura y ciencias ambientales',
  'Informática y tecnología de la información',
  'Periodismo y comunicación'
];

const educational = [
  'Secundaria',
  'Bachillerato +1',
  'Bachillerato +2',
  'Bachillerato +3',
  'Bachillerato +4',
  'Bachillerato +5',
  'Bachillerato +6',
  'Bachillerato +7',
  'Bachillerato +8'
];

const activity = [
  'Actividades de servicios administrativos y de apoyo',
  'Actividades de hogares como empleadores',
  'Actividades extraterritoriales',
  'Actividades financieras y de seguros',
  'Actividades inmobiliarias',
  'Actividades especializadas, científicas y técnicas',
  'Administración pública y defensa; seguridad social obligatoria',
  'Agricultura, silvicultura y pesca',
  'Artes, espectáculos y actividades recreativas',
  'Comercio al por mayor y al por menor, reparación de vehículos automotores y motocicletas',
  'Construcción',
  'Enseñanza',
  'Extracción minera y explotación de canteras',
  'Hospedaje y servicios de comidas',
  'Industria manufacturera',
  'Información y comunicación',
  'Producción y distribución de agua',
  'Producción y distribución de electricidad, gas',
  'Salud humana y servicios sociales',
  'Transporte y almacenamiento',
  'Otras actividades de servicios'
];

const sport = [
  'Aikido',
  'Atletismo',
  'Remo',
  'Bádminton',
  'Béisbol',
  'Baloncesto',
  'Biatlón',
  'Billar',
  'BMX',
  'Boxeo',
  'Canoa-kayak',
  'Lucha libre',
  'Críquet',
  'Ciclismo',
  'Danza',
  'Ajedrez',
  'Equitación',
  'Escalada',
  'Esgrima',
  'Fútbol',
  'Fútbol americano',
  'Golf',
  'Gimnasia',
  'Balonmano',
  'Hockey sobre hielo',
  'Judo',
  'Kárate',
  'Kickboxing',
  'Lucha',
  'Natación',
  'Patinaje artístico',
  'Petanca',
  'Clavados',
  'Rugby',
  'Esquí',
  'Squash',
  'Surf',
  'Taekwondo',
  'Tenis',
  'Tenis de mesa',
  'Tiro con arco',
  'Triatlón',
  'Voleibol',
  'Waterpolo',
  'Yoga'
];

const transport = [
  'Avión - Licencia de piloto',
  'Barco - Licencia de navegación',
  'Autobús - Licencia D',
  'Camión - Licencia C',
  'Carro a vela',
  'Ciclomotor - Permiso BSR o Licencia AM',
  'Equipos de construcción - CACES',
  'Ferry',
  'Helicóptero - Licencia de piloto de helicóptero',
  'Motocicleta - Licencia A',
  'Metro',
  'Parapente - Licencia de piloto de parapente',
  'Permiso B o Permiso A1',
  'RER',
  'Patinete - Permiso BSR o Licencia AM',
  'Tractor - Licencia de conducir de la categoría adecuada según el peso'
];

const nationality = [
  'Afgano',
  'Albanés',
  'Argelino',
  'Alemán',
  'Estadounidense',
  'Andorrano',
  'Angoleño',
  'Antiguan',
  'Argentino',
  'Armenio',
  'Australiano',
  'Austriaco',
  'Azerbaiyano',
  'Bahamés',
  'Bahreiní',
  'Bangladesí',
  'Barbadense',
  'Bielorruso',
  'Belga',
  'Beliceño',
  'Beninés',
  'Bhutanes',
  'Boliviano',
  'Bosnio',
  'Botsuano',
  'Brasileño',
  'Británico',
  'Brunés',
  'Búlgaro',
  'Burkinabé',
  'Burundés',
  'Camboyano',
  'Camerunés',
  'Canadiense',
  'Cabo Verde',
  'Centroafricano',
  'Chileno',
  'Chino',
  'Chipriota',
  'Colombiano',
  'Comorense',
  'Congoleño',
  'Coreano',
  'Costarricense',
  'Croata',
  'Cubano',
  'Danés',
  'Yibutiano',
  'Dominicano',
  'Egipcio',
  'Emiratí',
  'Ecuatoriano',
  'Eritreo',
  'Español',
  'Estonio',
  'Etíope',
  'Fiyiano',
  'Finlandés',
  'Francés',
  'Gabonés',
  'Gambiano',
  'Georgiano',
  'Ghanés',
  'Griego',
  'Granadino',
  'Guatemalteco',
  'Guineano',
  'Guyanés',
  'Haitiano',
  'Hondureño',
  'Húngaro',
  'Indio',
  'Indonesio',
  'Iraquí',
  'Iraní',
  'Irlandés',
  'Islandés',
  'Israelí',
  'Italiano',
  'Marfileño',
  'Jamaicano',
  'Japonés',
  'Jordano',
  'Kazajo',
  'Keniano',
  'Kirguís',
  'Kiribatiano',
  'Kuwaití',
  'Laosiano',
  'Lesotense',
  'Letón',
  'Libanés',
  'Liberiano',
  'Libio',
  'Liechtensteiniano',
  'Lituano',
  'Luxemburgués',
  'Macedonio',
  'Malasio',
  'Malauí',
  'Maldivo',
  'Malgache',
  'Maliense',
  'Maltés',
  'Marroquí',
  'Marshallés',
  'Mauriciano',
  'Mauritano',
  'Mexicano',
  'Micronesio',
  'Moldavo',
  'Monegasco',
  'Mongol',
  'Montenegrino',
  'Mozambiqueño',
  'Namibio',
  'Nauruano',
  'Neerlandés',
  'Neozelandés',
  'Nepalí',
  'Nicaragüense',
  'Nigeriano',
  'Nigerino',
  'Norcoreano',
  'Noruego',
  'Omaní',
  'Ugandés',
  'Uzbeko',
  'Pakistani',
  'Palaos',
  'Palestino',
  'Panameño',
  'Papú Neoguineano',
  'Paraguayo',
  'Peruano',
  'Filipino',
  'Polaco',
  'Portugués',
  'Catarí',
  'Rumano',
  'Ruso',
  'Ruandés',
  'San Luciano',
  'Sanmarinense',
  'San Vicentino y Granadinense',
  'Salomonense',
  'Salvadoreño',
  'Samoano',
  'Santomense',
  'Saudí',
  'Senegalés',
  'Serbio',
  'Seychellense',
  'Sierraleonés',
  'Singapurense',
  'Eslovaco',
  'Esloveno',
  'Somalí',
  'Sudanés',
  'Sudafricano',
  'Surcoreano',
  'Sursudanés',
  'Surinamés',
  'Sueco',
  'Suizo',
  'Sirio',
  'Tayiko',
  'Tanzano',
  'Chadiano',
  'Checo',
  'Tailandés',
  'Timorense',
  'Togolés',
  'Tongano',
  'Trinitense',
  'Tunecino',
  'Turco',
  'Turcomano',
  'Tuvaluano',
  'Ucraniano',
  'Uruguayo',
  'Vanuatuense',
  'Venezolano',
  'Vietnamita',
  'Yemení',
  'Zambiano',
  'Zimbabuense'
];

export { educational, domain, activity, sport, transport, nationality };
export default domain;
