import Head from "next/head";

import { LoginForm } from "../../components/login/LoginForm";

export default function SignIn() {
  return (
    <>
      <Head>
        <title>ECO2IA</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/eco2it_logo.jpeg" />
      </Head>
      <LoginForm />
    </>
  );
}
SignIn.getLayout = (page) => page;
