// pages/auth/signin.js
import { useRouter } from 'next/router';
import { useState } from 'react';
import { signIn } from 'next-auth/react';
import Image from 'next/image';
import logo from '../../public/Mlogop.png';
import login_image from '../../public/login_image.png';
import { DataSignin } from '../../data/signin';
import Head from 'next/head';
import Link from 'next/link';
import Register from '../../components/register/register';
import { isValidEmail } from '../../util/helpers/valid_email';
import { toast, Toaster } from 'react-hot-toast';

export default function SignIn() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const onSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    if (!isValidEmail(email)) {
      toast.error('Email invalide');
      setIsLoading(false);
      return;
    }

    try {
      const result = await signIn('credentials', {
        email,
        password,
        redirect: false //
      });

      if (result?.error) {
        if (
          result.error.includes('email') ||
          result.error.includes('password')
        ) {
          toast.error("L'adresse e-mail ou le mot de passe est incorrect.");
        } else {
          toast.error("L'adresse e-mail ou le mot de passe est incorrect. ");
        }
      } else {
        // Si no hubo errores, puedes redirigir manualmente al dashboard aquí.
        router.push('/dashboard');
      }
    } catch (error) {
      console.error(error);
      toast.error("Une erreur inattendue s'est produite");
    }

    setIsLoading(false);
  };

  const handleModalRegister = () => {
    // Handle button click logic here

    setIsModalOpen(!isModalOpen); // Set the state to open the modal
  };

  return (
    <div className="flex">
      <Head>
        <title>Mattech</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/Mlogo.ico" />
      </Head>
      <div className="flex flex-1 flex-col justify-center py-8 px-8 pb-36 sm:px-6 lg:flex-none lg:px-20 xl:px-24 bg-gray-900">
        <div className="mx-auto w-full max-w-sm lg:w-96">
          <Image className="h-12 w-auto" src={logo} alt="Mattech" />
          <h2 className="mt-6 text-3xl font-bold tracking-tight text-white">
            {DataSignin.signintitle}
          </h2>
          <p className="mt-2 text-sm text-white">
            {' '}
            <a
              href="#"
              className="font-medium text-indigo-600 hover:text-indigo-500"
            ></a>
          </p>

          <div className="mt-8">
            <div>
              <div className="relative mt-6">
                <div
                  className="absolute inset-0 flex items-center"
                  aria-hidden="true"
                >
                  <div className="w-full border-t border-gray-300" />
                </div>
                <div className="relative flex justify-center text-sm">
                  <span className="bg-white px-2 text-gray-500">
                    {DataSignin.signinsubtitle2}
                  </span>
                </div>
              </div>
            </div>

            <div className="mt-6">
              <form className="space-y-6" onSubmit={onSubmit}>
                <div>
                  <label
                    htmlFor="email"
                    className="block text-sm font-medium leading-6 text-white"
                  >
                    {DataSignin.signinadress}
                  </label>
                  <div className="mt-2">
                    <input
                      id="email"
                      name="email"
                      type="email"
                      autoComplete="email"
                      required
                      value={email}
                      onChange={(event) => setEmail(event.target.value)}
                      className="block w-full rounded-md border-0 py-1.5 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    />
                  </div>
                </div>

                <div className="space-y-1">
                  <label
                    htmlFor="password"
                    className="block text-sm font-medium leading-6 text-white"
                  >
                    {DataSignin.signinpassword}
                  </label>
                  <div className="mt-2">
                    <input
                      id="password"
                      name="password"
                      type="password"
                      autoComplete="current-password"
                      required
                      value={password}
                      onChange={(event) => setPassword(event.target.value)}
                      className="block w-full rounded-md border-0 py-1.5 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    />
                  </div>
                </div>

                <div className="flex items-center justify-between">
                  <div className="flex items-center">
                    <input
                      id="remember-me"
                      name="remember-me"
                      type="checkbox"
                      className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600"
                    />
                    <label
                      htmlFor="remember-me"
                      className="ml-2 block text-sm text-white"
                    >
                      {DataSignin.signinremember}
                    </label>
                  </div>

                  <div className="text-sm">
                    <Link
                      href="/forgot-password"
                      className="font-medium text-indigo-600 hover:text-indigo-500"
                    >
                      {DataSignin.signinforgot}
                    </Link>
                  </div>
                </div>

                <div>
                  <button
                    type="submit"
                    className="flex w-full justify-center rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                    disabled={isLoading}
                  >
                    {isLoading
                      ? DataSignin.signinloading
                      : DataSignin.signinconnect}
                  </button>
                </div>
                {error && (
                  <h4 className="font-medium text-sm text-white"> {error}</h4>
                )}
                <div className="text-sm text-center">
                  <h4 className="font-medium text-sm text-white">ou</h4>
                </div>
                <div className="text-sm text-center">
                  <a
                    className="font-medium text-sm text-indigo-600 hover:text-indigo-500 cursor-pointer"
                    onClick={() => handleModalRegister()}
                  >
                    {DataSignin.CreateAccount}
                  </a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div className="relative hidden w-0 flex-1 lg:block ">
        <Image
          className="absolute inset-0 h-full w-full object-cover"
          src={login_image}
          alt="login image"
          priority
        />
      </div>
      {isModalOpen && <Register onClose={handleModalRegister} />}
      <Toaster position="top-center" />
    </div>
  );
}
SignIn.getLayout = (page) => page;
