import Head from 'next/head';
import TextSummarizerPage from '../components/eco2resum/TextSummarizer';
import Modal from '../components/modal/modal';
import { getUser } from '../util/api/user';

export default function Eco2Resume(props) {
  return (
    <div className="py-10">
      <Head>
        <title>ECO2RESUME</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/eco2it_logo.jpeg" />
      </Head>
      {/* {!props.user.plan ? (
        <Modal user={props?.user} />
      ) : +props?.user?.plan?.max_tokens <= 0 ? (
        <Modal user={props?.user} />
      ) : (
        <TextSummarizerPage user={props.user.id} />
      )} */}
      {props.user.plan.typo === 'Freemium' ||
      props.user.plan.typo === 'Standard' ? (
        <Modal user={props?.user} />
      ) : +props?.user?.plan?.max_tokens <= 0 ? (
        <Modal user={props?.user} />
      ) : (
        <TextSummarizerPage user={props.user.id} />
      )}
      {/* <TextSummarizerPage user={props.user.id} /> */}
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const result = await getUser(context);

  if (!result?.data) {
    return {
      redirect: {
        permanent: false,
        destination: '/'
      }
    };
  }

  return {
    props: {
      user: result?.data,
      session: result?.session
    }
  };
};
