import Head from 'next/head';
// import Modal from '../components/modal/modal';
import Eco2cvIA from '../components/eco2cv/Eco2cv';
import { getUser } from '../util/api/user';

const Eco2cv = (props) => {
  return (
    <div>
      <Head>
        <title>ECO2CV</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/eco2it_logo.jpeg" />
      </Head>
      {/* {!props.user.plan ? (
        <Modal user={props?.user} />
      ) : +props?.user?.plan?.max_tokens <= 0 ? (
        <Modal user={props?.user} />
      ) : (
        <Eco2cvIA />
      )} */}
      <Eco2cvIA />
    </div>
  );
};

export const getServerSideProps = async (context) => {
  const result = await getUser(context);

  if (!result?.data) {
    return {
      redirect: {
        permanent: false,
        destination: '/'
      }
    };
  }

  return {
    props: {
      user: result?.data,
      session: result?.session
    }
  };
};

export default Eco2cv;
