import Head from 'next/head';
import DalleIA from '../components/dalle/dalle';
// import Modal from "../components/modal/modal";
import { getUser } from '../util/api/user';

export default function Dalle() {
  return (
    <div>
      <Head>
        <title>ECO2IMAGE</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/eco2it_logo.jpeg" />
      </Head>

      <DalleIA />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const result = await getUser(context);

  if (!result) {
    return {
      redirect: {
        permanent: false,
        destination: '/'
      }
    };
  }

  return {
    props: {
      user: result?.data,
      session: result?.session
    }
  };
};
