import Head from 'next/head';
import ChatGpt from '../components/chatgpt/chatgpt';
import Modal from '../components/modal/modal';
import { getUser } from '../util/api/user';

export default function chatgpt(props) {
  const iasAccessArray = props?.user?.plan?.ias_access
    ? props.user.plan.ias_access.split(',').map((item) => item.trim())
    : [];

  const isEco2ChatAvailable = iasAccessArray.includes('Eco2Chat');

  return (
    <div className="my-10">
      <Head>
        <title>ECO2CHAT</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/eco2it_logo.jpeg" />
      </Head>

      {/* If it is not a plan, or the plan does not have access to chatGpt, or the user has no tokens, show the modal */}
      {!props.user.plan ? (
        <Modal user={props?.user} />
      ) : !isEco2ChatAvailable ? (
        <Modal user={props?.user} />
      ) : +props?.user?.plan?.max_tokens <= 0 ? (
        <Modal user={props?.user} />
      ) : (
        <ChatGpt user={props.user.id} />
      )}
    </div>
  );
}
export const getServerSideProps = async (context) => {
  const result = await getUser(context);

  if (!result?.data) {
    return {
      redirect: {
        permanent: false,
        destination: '/'
      }
    };
  }

  return {
    props: {
      user: result?.data,
      session: result?.session
    }
  };
};
