import Head from "next/head";
import { getUser } from "../util/api/user";
import Modal from "../components/modal/modal";

import StepsLayout from "../components/steps_renovhome/StepsLayout"

export default function renovhome(props) {
  return (
    <div>
      <Head>
        <title>ECO2RENOVHOME</title>
        <meta name="description" content="Generated by ECO² Colombia" />
        <link rel="icon" href="/Mlogo.ico" />
      </Head>
      {!props.user.plan ? (
        <Modal user={props?.user} />
      ) : +props?.user?.plan?.max_tokens <= 0 ? (
        <Modal user={props?.user} />
      ) : (
        
      <StepsLayout />
      )}
    </div>
  );
}




export const getServerSideProps = async (context) => {
  const result = await getUser(context);

  if (!result?.data) {
    return {
      redirect: {
        permanent: false,
        destination: '/'
      }
    };
  }

  return {
    props: {
      user: result?.data,
      session: result?.session
    }
  };
};
